import LocalizedStrings from "react-localization";

const translations = new LocalizedStrings({
  en: {
    title: "🇬🇧 English",
    home: "Home",
    cryptocurrencies: "Cryptocurrencies",
    news: "News",
    globalStats: "Global Crypto Stats",
    totalCryptos: "Total Cryptocurrencies",
    totalExchanges: "Total Exchanges",
    totalMarketCap: "Total Market Cap",
    total24hVolume: "Total 24h Volume",
    totalMarkets: "Total Markets",
    top10: "Top 10 Cryptocurrencies in the world",
    showMore: "Show More",
    latestNews: "Latest Crypto News",
    searchCryptocurrency: "Search Cryptocurrency",
    price: "Price",
    marketCap: "Market Cap",
    dailyChange: "Daily Change",
    priceStatistics: "Price Statistics",
    minimumPrice: "Minimum Price",
    maximumPrice: "Maximum Price",
    averagePrice: "Average Price",
    valueStatistics: "Value Statistics",
    otherStatsInfo: "Other Stats Info",
    numberOfMarkets: "Number Of Markets",
    numberOfExchanges: "Number Of Exchanges",
    approvedSupply: "Approved Supply",
    totalSupply: "Total Supply",
    circulatingSupply: "Circulating Supply",
    whatIs: "What is",
    links: "Links",
    searchNews: "Search News",
    didntFindNews: "Didn't find the news? 😢",
    didntFindCrypto: "Didn't find the cryptocurrency? 😢",
    searchOnGoogle: "Let's search on Google! 🚀",
    tryAgain: "Try Again",
  },
  lv: {
    title: "🇱🇻 Latviešu",
    home: "Sākums",
    cryptocurrencies: "Kriptovalūtas",
    news: "Ziņas",
    globalStats: "Globālā kripto statistika",
    totalCryptos: "Kopējās kriptovalūtas",
    totalExchanges: "Kopējās biržas",
    totalMarketCap: "Kopējā tirgus kapitalizācija",
    total24hVolume: "Kopējais 24h apjoms",
    totalMarkets: "Kopējie tirgi",
    top10: "Top 10 kriptovalūtas pasaulē",
    showMore: "Rādīt vairāk",
    latestNews: "Jaunākās kripto ziņas",
    searchCryptocurrency: "Meklēt kriptovalūtu",
    price: "Cena",
    marketCap: "Tirgus kapitalizācija",
    dailyChange: "Dienas izmaiņas",
    priceStatistics: "Cenu statistika",
    minimumPrice: "Minimālā cena",
    maximumPrice: "Maksimālā cena",
    averagePrice: "Vidējā cena",
    valueStatistics: "Vērtības statistika",
    otherStatsInfo: "Cita statistika",
    numberOfMarkets: "Tirgu skaits",
    numberOfExchanges: "Biržu skaits",
    approvedSupply: "Apstiprinātā piegāde",
    totalSupply: "Kopējā piegāde",
    circulatingSupply: "Aprites piegāde",
    whatIs: "Kas ir",
    links: "Saites",
    searchNews: "Meklēt ziņas",
    didntFindNews: "Neatradāt ziņas? 😢",
    didntFindCrypto: "Neatradāt kriptovalūtu? 😢",
    searchOnGoogle: "Meklēsim Google! 🚀",
    tryAgain: "Mēģiniet vēlreiz",
  },
  ru: {
    title: "🇷🇺 Русский",
    home: "Главная",
    cryptocurrencies: "Криптовалюты",
    news: "Новости",
    globalStats: "Глобальная крипто-статистика",
    totalCryptos: "Всего криптовалют",
    totalExchanges: "Всего бирж",
    totalMarketCap: "Общая капитализация",
    total24hVolume: "Объем за 24ч",
    totalMarkets: "Всего рынков",
    top10: "Топ-10 криптовалют мира",
    showMore: "Показать больше",
    latestNews: "Последние новости о криптовалюте",
    searchCryptocurrency: "Поиск криптовалюты",
    price: "Цена",
    marketCap: "Капитализация",
    dailyChange: "Изменение за день",
    priceStatistics: "Статистика цен",
    minimumPrice: "Минимальная цена",
    maximumPrice: "Максимальная цена",
    averagePrice: "Средняя цена",
    valueStatistics: "Статистика стоимости",
    otherStatsInfo: "Другая статистика",
    numberOfMarkets: "Количество рынков",
    numberOfExchanges: "Количество бирж",
    approvedSupply: "Подтвержденный объем",
    totalSupply: "Общий объем",
    circulatingSupply: "Объем в обращении",
    whatIs: "Что такое",
    links: "Ссылки",
    searchNews: "Поиск новостей",
    didntFindNews: "Не нашли новости? 😢",
    didntFindCrypto: "Не нашли криптовалюту? 😢",
    searchOnGoogle: "Поищем в Google! 🚀",
    tryAgain: "Попробовать снова",
  },
});

translations.setLanguage(localStorage.getItem("lang") || "en");

console.log("Initial translationsObject:", translations);

export default translations;